name: Build, Test & Deploy Flask application

on:
  push:
    branches:
      - staging
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Install Flask
        run: pip install flask

      - name: Run Flask Application
        run: python app.py &
  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          
      - name: Set executable permission
        run: chmod +x test_app.py

      - name: Install Flask
        run: pip install flask

      - name: Install pytest
        run: pip install pytest


      - name: Test Python code
        run: pytest test_app.py
      
        
  deploy_staging:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy to Staging
      run: |
        git config --global user.email "mohankandikuppa119@gmail.com"
        git config --global user.name "mohankrishna"
        git add .
        git commit -m "deploying into staging"
        git push
        # Your staging deployment commands here
        echo "Deploying to staging..."

  deploy_production:
    runs-on: ubuntu-latest

    needs: deploy_staging

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy to Production
      run: |
        # Your production deployment commands here
        git config --global user.email "mohankandikuppa119@gmail.com"
        git config --global user.name "mohankrishna"
        git add . 
        git commit -m "deploying into main"
        git push origin main
        echo "Deploying to main..."

    - name: Tag and Release
      run: |
        # Create a version tag
        git tag -a v1.0 -m "Version 1.0"
        git push origin v1.0

        # Your release commands here
        echo "Tagged and released version 1.0"
          

     
