name: Deploy to staging and Main
on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install flask
        run: pip install flask

      - name: run the flask application
        run: python app.py

      - name: Install pytest
        run: pip install pytest

      - name: Test Python code
        run: python test_script.py
