name: Ec2-deployment

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: code checkout
        uses: actions/checkout@v2

      - name: install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          sudo pip install flask
          sudo pip install streamlit
          sudo pip install pytest
      - name: Run Flask Application
        run: sudo python app.py &

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: build and test
        run: |
          # testing scripts
          sudo pytest test_app.py

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: deployment step
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/ubuntu/
            git clone https://github.com/mohanvedase/CICD_GitHubActions_Jenkins.git
            apt install -y python3-pip
            pip install flask
            # sudo python3 /home/ubuntu/Jenkins/app.py
