#!/bin/bash

# Set the path to your repository
repo_path="/home/ubuntu/CICD_GitActions"

# Set the branches
staging_branch="staging"
main_branch="main"

# Set the version
version="v1.0"

# Change directory to the repository
cd "$repo_path"

# Pull the latest changes from the staging branch
git pull origin "$staging_branch"

# Check if there are uncommitted changes in the staging branch
if git diff --quiet; then
  echo "No code changes detected. Skipping deployment."
else
  # Install or update dependencies (if needed)
  sudo apt update
  sudo apt install -y python3-pip
  sudo pip install -r requirements.txt

  # Optionally, stop the existing application (if running)
  # ...

  # Start your application (e.g., Flask app)
  nohup python app.py &
  pytest test_app.py

  # Optionally, run additional deployment tasks

  # Stage all changes
  git add .

  # Commit all changes with a descriptive message
  git commit -m "Deploy changes from $staging_branch to $main_branch"

  # Tag the commit with the version
  git tag -a "$version" -m "Release version $version"

  # Push the committed changes and the tag to the main branch
  git push origin main --tags

  echo "Changes and version $version pushed to $main_branch branch."
fi
