name: Build, Test & Deploy Flask application

on:
  push:
    branches:
      - staging
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Install Flask
        run: pip install flask

      - name: Run Flask Application
        run: python app.py &
  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          
      - name: Set executable permission
        run: chmod +x test_app.py

      - name: Install Flask
        run: pip install flask

      - name: Install pytest
        run: pip install pytest


      - name: Test Python code
        run: pytest test_app.py
      
        
  
  deploy_production:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy to Main
      run: |
    - name: SSH into EC2 Instance
      uses: appleboy/ssh-action@v1.0.0
      with:
       host: ${{ secrets.EC2_HOST }}
       username: ${{ secrets.EC2_USERNAME }}
       key: ${{ secrets.SSH_PRIVATE_KEY }}
       port: ${{ secrets.PORT }}
       script: |
        git clone https://github.com/mohanvedase/CICD_GitHubActions_Jenkins.git
        cd /home/ubuntu/CICD_GitHubActions_Jenkins.git
        git checkout staging
        git pull origin staging
        git checkout main
        git push origin staging:main --force
        #git add .
        #git push origin main 

   

  
          

     
